/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tag?: "For Sale" | "For Rent";
  price?: number;
  title?: string;
  description?: string;
  location?: string;
  beds?: number;
  baths?: number;
  sqft?: string;
  type?:
    | "Apartment"
    | "Townhouse"
    | "Detached"
    | "Semi-Detached"
    | "Flat"
    | "Manor"
    | "Terraced"
    | "Penthouse";
  featured?: boolean;
  amenities?: Array<string>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Property
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/property/getAllProperties.ts
// Variable: ALL_PROPERTIES_QUERY
// Query: *[_type == "property"] | order(_createdAt desc) {			_id,			tag,			price,			title,			location,			beds,			baths,			sqft,			type,			featured,			images[]{				asset->{					url				},				alt			}		}
export type ALL_PROPERTIES_QUERY_RESULT = Array<{
  _id: string;
  tag: "For Rent" | "For Sale" | null;
  price: number | null;
  title: string | null;
  location: string | null;
  beds: number | null;
  baths: number | null;
  sqft: string | null;
  type:
    | "Apartment"
    | "Detached"
    | "Flat"
    | "Manor"
    | "Penthouse"
    | "Semi-Detached"
    | "Terraced"
    | "Townhouse"
    | null;
  featured: boolean | null;
  images: Array<{
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/property/getPropertyById.ts
// Variable: PROPERTY_BY_ID_QUERY
// Query: *[_type == "property" && _id == $id][0] {			_id,			tag,			price,			title,			location,			beds,			baths,			sqft,			type,			featured,			images[]{				asset->{					url				},				alt			}		}
export type PROPERTY_BY_ID_QUERY_RESULT = {
  _id: string;
  tag: "For Rent" | "For Sale" | null;
  price: number | null;
  title: string | null;
  location: string | null;
  beds: number | null;
  baths: number | null;
  sqft: string | null;
  type:
    | "Apartment"
    | "Detached"
    | "Flat"
    | "Manor"
    | "Penthouse"
    | "Semi-Detached"
    | "Terraced"
    | "Townhouse"
    | null;
  featured: boolean | null;
  images: Array<{
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n\t\t*[_type == "property"] | order(_createdAt desc) {\n\t\t\t_id,\n\t\t\ttag,\n\t\t\tprice,\n\t\t\ttitle,\n\t\t\tlocation,\n\t\t\tbeds,\n\t\t\tbaths,\n\t\t\tsqft,\n\t\t\ttype,\n\t\t\tfeatured,\n\t\t\timages[]{\n\t\t\t\tasset->{\n\t\t\t\t\turl\n\t\t\t\t},\n\t\t\t\talt\n\t\t\t}\n\t\t}\n\t': ALL_PROPERTIES_QUERY_RESULT;
    '\n\t\t*[_type == "property" && _id == $id][0] {\n\t\t\t_id,\n\t\t\ttag,\n\t\t\tprice,\n\t\t\ttitle,\n\t\t\tlocation,\n\t\t\tbeds,\n\t\t\tbaths,\n\t\t\tsqft,\n\t\t\ttype,\n\t\t\tfeatured,\n\t\t\timages[]{\n\t\t\t\tasset->{\n\t\t\t\t\turl\n\t\t\t\t},\n\t\t\t\talt\n\t\t\t}\n\t\t}\n\t': PROPERTY_BY_ID_QUERY_RESULT;
  }
}
