/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type UserListing = {
  _id: string;
  _type: "userListing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  status?: "pending" | "active" | "rejected";
  plan?: string;
  tag?: "For Sale" | "For Rent";
  price?: number;
  title?: string;
  description?: string;
  location?: string;
  beds?: number;
  baths?: number;
  sqft?: string;
  type?:
    | "Apartment"
    | "Townhouse"
    | "Detached"
    | "Semi-Detached"
    | "Flat"
    | "Manor"
    | "Terraced"
    | "Penthouse";
  amenities?: Array<string>;
  contactEmail?: string;
  contactPhone?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tag?: "For Sale" | "For Rent";
  price?: number;
  title?: string;
  description?: string;
  location?: string;
  beds?: number;
  baths?: number;
  sqft?: string;
  type?:
    | "Apartment"
    | "Townhouse"
    | "Detached"
    | "Semi-Detached"
    | "Flat"
    | "Manor"
    | "Terraced"
    | "Penthouse";
  featured?: boolean;
  amenities?: Array<string>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | UserListing
  | SanityImageCrop
  | SanityImageHotspot
  | Property
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/property/getAllProperties.ts
// Variable: QUERY
// Query: *[			(_type == "property") ||			(_type == "userListing" && status == "active")		] | order(_createdAt desc) {				_id,	_type,	tag,	price,	title,	location,	beds,	baths,	sqft,	type,	featured,	images[]{		_key,		asset->{			url		},		alt	}		}
export type QUERY_RESULT = Array<
  | {
      _id: string;
      _type: "property";
      tag: "For Rent" | "For Sale" | null;
      price: number | null;
      title: string | null;
      location: string | null;
      beds: number | null;
      baths: number | null;
      sqft: string | null;
      type:
        | "Apartment"
        | "Detached"
        | "Flat"
        | "Manor"
        | "Penthouse"
        | "Semi-Detached"
        | "Terraced"
        | "Townhouse"
        | null;
      featured: boolean | null;
      images: Array<{
        _key: string;
        asset: {
          url: string | null;
        } | null;
        alt: string | null;
      }> | null;
    }
  | {
      _id: string;
      _type: "userListing";
      tag: "For Rent" | "For Sale" | null;
      price: number | null;
      title: string | null;
      location: string | null;
      beds: number | null;
      baths: number | null;
      sqft: string | null;
      type:
        | "Apartment"
        | "Detached"
        | "Flat"
        | "Manor"
        | "Penthouse"
        | "Semi-Detached"
        | "Terraced"
        | "Townhouse"
        | null;
      featured: null;
      images: Array<{
        _key: string;
        asset: {
          url: string | null;
        } | null;
        alt: string | null;
      }> | null;
    }
>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n\t\t*[\n\t\t\t(_type == "property") ||\n\t\t\t(_type == "userListing" && status == "active")\n\t\t] | order(_createdAt desc) {\n\t\t\t\n\t_id,\n\t_type,\n\ttag,\n\tprice,\n\ttitle,\n\tlocation,\n\tbeds,\n\tbaths,\n\tsqft,\n\ttype,\n\tfeatured,\n\timages[]{\n\t\t_key,\n\t\tasset->{\n\t\t\turl\n\t\t},\n\t\talt\n\t}\n\n\t\t}\n\t': QUERY_RESULT;
  }
}
